apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type:

  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    author: Bharath
    type: reverse-proxy
---

