apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: default
data:
  enableCadi: "false"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: "40000"
  KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: "40000"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL_PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT"
  KAFKA_ADVERTISED_LISTENERS: "INTERNAL_PLAINTEXT://kafka:9092"
  KAFKA_LISTENERS: "INTERNAL_PLAINTEXT://0.0.0.0:9092"
  KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL_PLAINTEXT"
  KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
  KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/jaas/zk_client_jaas.conf"
  KAFKA_ZOOKEEPER_SET_ACL: "true"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  # Reduced the number of partitions only to avoid the timeout error for the first subscribe call in slow environment
  KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: "1"
  # You can add other Kafka configurations here as needed
