apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-deployment
  template:
    metadata:
      labels:
        app: kafka-deployment
    spec:
      containers:
        - name: kafka
          image: nexus3.onap.org:10001/onap/dmaap/kafka111:1.0.4
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: kafka-config

---

